Repository cs361w2019-osu/sprint1-project-group-15, pull requests merged in 2019-03, with the labels that each got.

#54 Initial front-end implementation of submarine
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
  src/main/java/controllers/ApplicationController.java
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/cs361/battleships/models/Ship.java
  src/main/java/cs361/battleships/models/Submarine.java
  src/main/java/views/ApplicationController/index.ftl.html
  src/test/java/cs361/battleships/models/BoardTest.java
Labels: feature

#56 Submarine placement front-end fixes
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
Labels: bug

#57 Is48
  README
  src/main/java/assets/game.js
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/cs361/battleships/models/Ship.java
  src/main/java/cs361/battleships/models/Submarine.java
  src/test/java/cs361/battleships/models/BoardTest.java
  src/test/java/cs361/battleships/models/GameTest.java
  src/test/java/cs361/battleships/models/SquareTest.java
  src/test/java/cs361/battleships/models/SubmarineTest.java
Labels: Story 4, bug, feature, sprint-4

#59 Issue49 take2
  src/main/java/assets/game.js
  src/main/java/conf/Routes.java
  src/main/java/controllers/ApplicationController.java
  src/main/java/controllers/MovementGameAction.java
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/cs361/battleships/models/Ship.java
  src/main/java/cs361/battleships/models/Submarine.java
  src/main/java/views/ApplicationController/index.ftl.html
  src/test/java/cs361/battleships/models/BoardTest.java
  src/test/java/cs361/battleships/models/ShipTest.java
Labels: feature
