Repository cs361w2019-osu/sprint1-project-group-15, pull requests merged in 2019-02, with the labels that each got.

#22 Board switching + Bug fixes
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/views/ApplicationController/index.ftl.html
Labels: bug, enhancement

#23 Implement Error Modal
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
  src/main/java/views/ApplicationController/index.ftl.html
  src/main/java/views/layout/defaultLayout.ftl.html
  src/main/java/views/layout/error_modal.ftl.html
Labels: enhancement

#25 added surrender option
  src/main/java/assets/game.js
  src/main/java/views/ApplicationController/index.ftl.html
Labels: enhancement

#26 implemented rotate keyboard shortcut
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
  src/main/java/views/ApplicationController/index.ftl.html
Labels: enhancement

#28 Fixed highlighting while using shortcut
  src/main/java/assets/game.js
Labels: bug

#29 Added Auto Ship Placement
  README
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
  src/main/java/views/ApplicationController/index.ftl.html
Labels: enhancement

#40 Issue33
  src/main/java/cs361/battleships/models/AttackStatus.java
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/cs361/battleships/models/Result.java
Labels: Refactor

#39 Initial implementation of Captain's Quarters
  src/main/java/cs361/battleships/models/Ship.java
  src/test/java/cs361/battleships/models/BoardTest.java
Labels: feature

#38 Initial Implementation for Sonar Pulse
  src/main/java/assets/game.js
Labels: bug, feature

#43 Captain's quarter sinking implemented
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/CaptainsQuarter.java
  src/main/java/cs361/battleships/models/Ship.java
  src/test/java/cs361/battleships/models/AttackSpecialCases.java
  src/test/java/cs361/battleships/models/BoardTest.java
Labels: feature

#45 Issue32
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/cs361/battleships/models/OpponentBoard.java
  src/test/java/cs361/battleships/models/BoardTest.java
  src/test/java/cs361/battleships/models/OpponentBoardTest.java
Labels: Refactor

#47 Is41
  src/main/java/assets/game.js
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/CaptainsQuarter.java
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/cs361/battleships/models/Ship.java
  src/test/java/cs361/battleships/models/BoardTest.java
Labels: bug, feature
