Repository cs361w2019-osu/sprint1-project-group-15, pull requests merged in 2019-01, with the labels that each got.

#6 Implemented Result class
  src/main/java/cs361/battleships/models/Result.java
Labels: Story 6

#11 Fixed small typo in for loop
  src/main/java/cs361/battleships/models/Board.java
Labels: bug

#13 Test Beautification complete
  src/test/java/cs361/battleships/models/AttackSpecialCases.java
Labels: Refactor
